import json

import requests
from bs4 import BeautifulSoup


def create_role():
    url = "http://localhost:8080/aaa/role"
    api = ""
    headers = {
        'content-type': 'application/json',
        'Authorization': 'WEB 9f2ae5c5-72f2-45e9-a37c-d2757cc32daf'
    }

    body = {
        "roleId": "testROLE",
        "roleName": "testROLE",
        "status": "ENABLED",
        "permissionIds": [
            "PUT /aaa/config/:configId",
            "GET /aaa/config",
            "DELETE /aaa",
            "PUT /aaa/password",
            "GET /aaa/guest",
            "PUT /aaa/guest",
            "POST /aaa/tenant",
            "GET /aaa/tenant/:tenantId",
            "PUT /aaa/tenant/:tenantId",
            "GET /aaa/tenant",
            "DELETE /aaa/tenant",
            "POST /aaa/subTenant",
            "GET /aaa/subTenant/:tenantId",
            "PUT /aaa/subTenant/:tenantId",
            "GET /aaa/subTenant",
            "DELETE /aaa/subTenant",
            "GET /aaa/permission",
            "POST /aaa/role",
            "GET /aaa/role/:roleId",
            "PUT /aaa/role/:roleId",
            "GET /aaa/role",
            "DELETE /aaa/role",
            "POST /aaa/user",
            "GET /aaa/user/:userId",
            "PUT /aaa/user/:userId",
            "GET /aaa/user",
            "DELETE /aaa/user",
            "PUT /aaa/user/:userId/password",
            "POST /aaa/unit",
            "GET /aaa/unit/:unitId",
            "PUT /aaa/unit/:unitId",
            "GET /aaa/unit",
            "DELETE /aaa/unit",
            "POST /aaa/group",
            "GET /aaa/group/:groupId",
            "PUT /aaa/group/:groupId",
            "GET /aaa/group",
            "DELETE /aaa/group",

            "POST /vitals/subject/:subjectId/ecg",
            "GET /vitals/subject/:subjectId/ecg",
            "GET /vitals/user/:userId/subject/:subjectId/ecg",
            "GET /vitals/provider/:userId/subject/:subjectId/ecg",
            "POST /vitals/subject/:subjectId/hrv",
            "GET /vitals/subject/:subjectId/hrv",
            "GET /vitals/user/:userId/subject/:subjectId/hrv",
            "GET /vitals/provider/:userId/subject/:subjectId/hrv",

            "POST /vitals/subject/:subjectId/bloodPressure",
            "GET /vitals/subject/:subjectId/bloodPressure",
            "GET /vitals/user/:userId/subject/:subjectId/bloodPressure",
            "POST /vitals/subject/:subjectId/bloodGlucose",
            "GET /vitals/subject/:subjectId/bloodGlucose",
            "GET /vitals/user/:userId/subject/:subjectId/bloodGlucose",
            "POST /vitals/subject/:subjectId/bodyTemperature",
            "GET /vitals/subject/:subjectId/bodyTemperature",
            "GET /vitals/user/:userId/subject/:subjectId/bodyTemperature",
            "POST /vitals/subject/:subjectId/bodyInfo",
            "GET /vitals/subject/:subjectId/bodyInfo",
            "GET /vitals/user/:userId/subject/:subjectId/bodyInfo",
            "POST /vitals/subject/:subjectId/waist",
            "GET /vitals/subject/:subjectId/waist",
            "GET /vitals/user/:userId/subject/:subjectId/waist",
            "POST /vitals/subject/:subjectId/biochemistry",
            "GET /vitals/subject/:subjectId/biochemistry",
            "GET /vitals/user/:userId/subject/:subjectId/biochemistry",
            "GET /abnormality/subject",
            "GET /abnormality/bloodPressure/case/:caseId",
            "GET /abnormality/bloodPressure/case",
            "POST /abnormality/bloodPressure/case/:caseId/log",
            "GET /abnormality/bloodPressure/case/:caseId/log/:logId",
            "GET /abnormality/bloodPressure/case/:caseId/log",
            "GET /vitals/provider/:userId/subject/:subjectId/biochemistry",
            "GET /vitals/provider/:userId/subject/:subjectId/bloodGlucose",
            "GET /vitals/provider/:userId/subject/:subjectId/bloodPressure",
            "GET /vitals/provider/:userId/subject/:subjectId/bodyInfo",
            "GET /vitals/provider/:userId/subject/:subjectId/bodyTemperature",
            "GET /vitals/provider/:userId/subject/:subjectId/waist",

            "POST /friend/:userId",
            "PUT /friend/agree/:sequence",
            "GET /friend/:userId",
            "GET /friend",
            "DELETE /friend/:sequence",
            "DELETE /friend",
            "POST /follow/:userId",
            "POST /follow",
            "GET /follow/:userId",
            "GET /follow/followme",
            "GET /follow",
            "DELETE /follow/:sequence",
            "DELETE /follow/userId/:userId",
            "POST /blocklist/:userId",
            "GET /blocklist",
            "GET /blocklist/:userId",
            "DELETE /blocklist/:sequence",

            "GET /questionnair/:questionnairId",
            "GET /questionnair",
            "GET /questionnair/:questionnairId/question/:questionId",
            "GET /questionnair/:questionnairId/question",
            "POST /questionnair/:questionnairId/reply",

            "POST /vitals/device",
            "GET /vitals/device/:deviceId",
            "PUT /vitals/device/:deviceId",
            "GET /vitals/device",
            "DELETE /vitals/device",
            "POST /vitals/subject",
            "PUT /vitals/subject/:subjectId",
            "DELETE /vitals/subject",
            "GET /vitals/subject/:subjectId",
            "GET /vitals/user/:userId/subject/:subjectId",
            "GET /vitals/user/:userId/subject",
            "POST /aaa/unitMeta",
            "GET /aaa/unitMeta/:unitId",
            "PUT /aaa/unitMeta/:unitId",
            "GET /aaa/unitMeta",
            "DELETE /aaa/unitMeta",
            "POST /ownership/request",
            "GET /ownership/request",
            "DELETE /ownership/consent",
            "PUT /ownership/consent/:ownershipId",
            "GET /ownership/consent",
            "DELETE /ownership/request",
            "GET /ownership/simpleUser",
            "GET /vitals/report/record",
            "GET /vitals/report/amount",
            "GET /vitals/report/amountByAge",
            "GET /abnormality/report/amount",
            "GET /vitals/report/opinion",
            "POST /import/initialization",
            "GET /vitals/measuredSubject"
        ]
    }

    res = requests.post(url, data=json.dumps(body), headers=headers)

    soup = BeautifulSoup(res.text, "html.parser")

    print(soup)


create_role()

body = {
    "roleId": "testROLE",
    "roleName": "testROLE",
    "status": "ENABLED",
    "permissionIds": [

        "PUT /aaa/config/:configId",
        "GET /aaa/config",
        "DELETE /aaa",
        "PUT /aaa/password",
        "GET /aaa/guest",
        "PUT /aaa/guest",
        "POST /aaa/tenant",
        "GET /aaa/tenant/:tenantId",
        "PUT /aaa/tenant/:tenantId",
        "GET /aaa/tenant",
        "DELETE /aaa/tenant",
        "POST /aaa/subTenant",
        "GET /aaa/subTenant/:tenantId",
        "PUT /aaa/subTenant/:tenantId",
        "GET /aaa/subTenant",
        "DELETE /aaa/subTenant",
        "GET /aaa/permission",
        "POST /aaa/role",
        "GET /aaa/role/:roleId",
        "PUT /aaa/role/:roleId",
        "GET /aaa/role",
        "DELETE /aaa/role",
        "POST /aaa/user",
        "GET /aaa/user/:userId",
        "PUT /aaa/user/:userId",
        "GET /aaa/user",
        "DELETE /aaa/user",
        "PUT /aaa/user/:userId/password",
        "POST /aaa/unit",
        "GET /aaa/unit/:unitId",
        "PUT /aaa/unit/:unitId",
        "GET /aaa/unit",
        "DELETE /aaa/unit",
        "POST /aaa/group",
        "GET /aaa/group/:groupId",
        "PUT /aaa/group/:groupId",
        "GET /aaa/group",
        "DELETE /aaa/group",

        "POST /vitals/subject/:subjectId/ecg",
        "GET /vitals/subject/:subjectId/ecg",
        "GET /vitals/user/:userId/subject/:subjectId/ecg",
        "GET /vitals/provider/:userId/subject/:subjectId/ecg",
        "POST /vitals/subject/:subjectId/hrv",
        "GET /vitals/subject/:subjectId/hrv",
        "GET /vitals/user/:userId/subject/:subjectId/hrv",
        "GET /vitals/provider/:userId/subject/:subjectId/hrv",

        "POST /vitals/subject/:subjectId/bloodPressure",
        "GET /vitals/subject/:subjectId/bloodPressure",
        "GET /vitals/user/:userId/subject/:subjectId/bloodPressure",
        "POST /vitals/subject/:subjectId/bloodGlucose",
        "GET /vitals/subject/:subjectId/bloodGlucose",
        "GET /vitals/user/:userId/subject/:subjectId/bloodGlucose",
        "POST /vitals/subject/:subjectId/bodyTemperature",
        "GET /vitals/subject/:subjectId/bodyTemperature",
        "GET /vitals/user/:userId/subject/:subjectId/bodyTemperature",
        "POST /vitals/subject/:subjectId/bodyInfo",
        "GET /vitals/subject/:subjectId/bodyInfo",
        "GET /vitals/user/:userId/subject/:subjectId/bodyInfo",
        "POST /vitals/subject/:subjectId/waist",
        "GET /vitals/subject/:subjectId/waist",
        "GET /vitals/user/:userId/subject/:subjectId/waist",
        "POST /vitals/subject/:subjectId/biochemistry",
        "GET /vitals/subject/:subjectId/biochemistry",
        "GET /vitals/user/:userId/subject/:subjectId/biochemistry",
        "GET /abnormality/subject",
        "GET /abnormality/bloodPressure/case/:caseId",
        "GET /abnormality/bloodPressure/case",
        "POST /abnormality/bloodPressure/case/:caseId/log",
        "GET /abnormality/bloodPressure/case/:caseId/log/:logId",
        "GET /abnormality/bloodPressure/case/:caseId/log",
        "GET /vitals/provider/:userId/subject/:subjectId/biochemistry",
        "GET /vitals/provider/:userId/subject/:subjectId/bloodGlucose",
        "GET /vitals/provider/:userId/subject/:subjectId/bloodPressure",
        "GET /vitals/provider/:userId/subject/:subjectId/bodyInfo",
        "GET /vitals/provider/:userId/subject/:subjectId/bodyTemperature",
        "GET /vitals/provider/:userId/subject/:subjectId/waist",

        "POST /friend/:userId",
        "PUT /friend/agree/:sequence",
        "GET /friend/:userId",
        "GET /friend",
        "DELETE /friend/:sequence",
        "DELETE /friend",
        "POST /follow/:userId",
        "POST /follow",
        "GET /follow/:userId",
        "GET /follow/followme",
        "GET /follow",
        "DELETE /follow/:sequence",
        "DELETE /follow/userId/:userId",
        "POST /blocklist/:userId",
        "GET /blocklist",
        "GET /blocklist/:userId",
        "DELETE /blocklist/:sequence",

        "GET /questionnair/:questionnairId",
        "GET /questionnair",
        "GET /questionnair/:questionnairId/question/:questionId",
        "GET /questionnair/:questionnairId/question",
        "POST /questionnair/:questionnairId/reply",

        "POST /vitals/device",
        "GET /vitals/device/:deviceId",
        "PUT /vitals/device/:deviceId",
        "GET /vitals/device",
        "DELETE /vitals/device",
        "POST /vitals/subject",
        "PUT /vitals/subject/:subjectId",
        "DELETE /vitals/subject",
        "GET /vitals/subject/:subjectId",
        "GET /vitals/user/:userId/subject/:subjectId",
        "GET /vitals/user/:userId/subject",
        "POST /aaa/unitMeta",
        "GET /aaa/unitMeta/:unitId",
        "PUT /aaa/unitMeta/:unitId",
        "GET /aaa/unitMeta",
        "DELETE /aaa/unitMeta",
        "POST /ownership/request",
        "GET /ownership/request",
        "DELETE /ownership/consent",
        "PUT /ownership/consent/:ownershipId",
        "GET /ownership/consent",
        "DELETE /ownership/request",
        "GET /ownership/simpleUser",
        "GET /vitals/report/record",
        "GET /vitals/report/amount",
        "GET /vitals/report/amountByAge",
        "GET /abnormality/report/amount",
        "GET /vitals/report/opinion",
        "POST /import/initialization",
        "GET /vitals/measuredSubject"

    ]
}
